name: Atualizar GIF no README

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch: 

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Escolher um número aleatório de 1 a 6
        run: echo "RANDOM_NUM=$((1 + RANDOM % 6))" >> $GITHUB_ENV

      - name: Atualizar o README.md
        run: |
          sed -i "s|smileyoncomputer[1-6].gif|smileyoncomputer$RANDOM_NUM.gif|g" README.md

      - name: Commit e push se houver mudanças
        run: |
          git config --global user.name "n3ur0cr45h"
          git config --global user.email "n3ur0cr45h@github.com"
          git add README.md
          git commit -m "Atualizando GIF no README" || exit 0
          git push


