name: Update README GIF

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Escolher um GIF aleatório
        run: |
          RANDOM_NUM=$((1 + RANDOM % 6))
          echo "SELECTED_GIF=smileyoncomputer$RANDOM_NUM.gif" >> $GITHUB_ENV

      - name: Atualizar README.md
        run: |
          sed -i "s|!\[Smiley\](.*)|![Smiley]($SELECTED_GIF)|" README.md

      - name: Commit e push se houver mudanças
        run: |
          git config --global user.name "n3ur0cr45h"
          git config --global user.email "n3ur0cr45h@github.com"
          git add README.md
          git commit -m "Atualizando GIF no README" || exit 0
          git push
